config/routes.rb
resources :lean_canvas_items, only: [:index, :create, :update, :destroy] do
  collection do
    get :lean_canvas
  end
end

app/models/lean_canvas_item.rb
class LeanCanvasItem < ActiveRecord::Base
  unloadable

  module Kind
    PROBLEM                   = 1  # 課題
    CUSTOMER_SEGMENTS         = 2  # 顧客セグメント
    UNIQUE_VALUE_PROPOSITION  = 3  # 独自の価値提案
    SOLUTION                  = 4  # ソリューション
    CHANNELS                  = 5  # チャネル
    REVENUE_STREAMS           = 6  # 収益の流れ
    COST_STRUCTURE            = 7  # コスト構造
    KEY_METRICS               = 8  # 主要指標
    UNFAIR_ADVANTAGE          = 9  # 圧倒的な優位性
  end

  def name_by_kind(kind)
    Kind.constants.each do |kind_name|
      if Kind.const_get(kind_name) == kind
        return kind_name
      end
    end
  end

  class << self
    def each_kind
      lean_canvas_items_map = {}
      Kind.constants.each do |kind_name|
        lean_canvas_items_map[kind_name] ||= []
        lean_canvas_items = where(kind: Kind.const_get(kind_name))
        if lean_canvas_items
          lean_canvas_items.each do |lean_canvas_item|
            lean_canvas_items_map[kind_name] << lean_canvas_item
          end
        end
      end
      lean_canvas_items_map
    end
  end
end

app/controllers/lean_canvas_items_controller.rb
class LeanCanvasItemsController < ApplicationController
  unloadable

  def index
    @lean_canvas_items_map = LeanCanvasItem.each_kind
  end

  def create
    @lean_canvas_item = LeanCanvasItem.new(lean_canvas_item_params)
    @lean_canvas_item.save
    redirect_to action: "index"
  end

  def update
    @lean_canvas_item = LeanCanvasItem.find(params[:id])
    @lean_canvas_item.update(lean_canvas_item_params)
    redirect_to action: "index"
  end

  def destroy
    @lean_canvas_item = LeanCanvasItem.find(params[:id])
    @lean_canvas_item.destroy
    redirect_to action: "index"
  end

  def lean_canvas
    @lean_canvas_items_map = LeanCanvasItem.each_kind
    respond_to do |format|
      format.svg
    end
  end

  private
  def lean_canvas_item_params
    params.require(:lean_canvas_item).permit(:kind, :value)
  end
end

app/helpers/lean_canvas_items_helper.rb
module LeanCanvasItemsHelper
end

app/views/lean_canvas_items/create.html.erb
<h2>LeanCanvasItemsController#create</h2>

app/views/lean_canvas_items/delete.html.erb
<h2>LeanCanvasItemsController#delete</h2>

app/views/lean_canvas_items/index.html.erb
<h2>LeanCanvas</h2>

<%= image_tag lean_canvas_lean_canvas_items_path(format: :svg) %>

<table border="1">
  <% @lean_canvas_items_map.each do |kind_name, lean_canvas_items| %>
    <tr>
      <th rowspan="<%= @lean_canvas_items_map[kind_name].count + 1 %>"><%= kind_name %></th>
      <% lean_canvas_items.each_with_index do |lean_canvas_item, index| %>
        <td>
          <%= form_for(lean_canvas_item) do |f| %>
            <%= f.text_field :value, value: lean_canvas_item.value %>
            <%= f.submit("更新") %>
          <% end %>
          <%= button_to "削除", lean_canvas_item, method: :delete %>
        </td>
        <% if lean_canvas_items.count > 0 && index != @lean_canvas_items_map[kind_name].count %>
          </tr>
          <tr>
        <% end %>
      <% end %>
      <td>
        <%= form_for(LeanCanvasItem.new, url: {action: :create}) do |f| %>
          <%= f.text_field :value %>
          <%= f.hidden_field(:kind, value: LeanCanvasItem::Kind.const_get(kind_name)) %>
          <%= f.submit("追加") %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/lean_canvas_items/lean_canvas.svg.erb
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg width="1000" height="600" xmlns="http://www.w3.org/2000/svg" xmlns:xlink= "http://www.w3.org/1999/xlink">
  <g id="outline">
    <rect width="1000" height="600" class="outside"/>
    <rect width="200" height="400" id="problem"/>
    <text x="10" y="25" fill="#ffffff" font-size="20"><tspan fill="#ffffff" font-weight="bold">PROBLEM</tspan></text>
    <% @lean_canvas_items_map[:PROBLEM].each_with_index do |lean_canvas_item, index| %>
      <text x="10" y="<%= 25 + 20 * (index + 1) %>" fill="#ffffff" font-size="15"><%= lean_canvas_item.value %></text>
    <% end %>

    <rect width="200" height="200" x="200" id="solution"/>
    <text x="210" y="25" fill="#ffffff" font-size="20"><tspan fill="#ffffff" font-weight="bold">SOLUTION</tspan></text>
    <% @lean_canvas_items_map[:SOLUTION].each_with_index do |lean_canvas_item, index| %>
      <text x="210" y="<%= 25 + 20 * (index + 1) %>" fill="#ffffff" font-size="15"><%= lean_canvas_item.value %></text>
    <% end %>

    <rect width="200" height="200" x="200" y="200" id="key_metrics"/>
    <text x="210" y="225" fill="#ffffff" font-size="20"><tspan fill="#ffffff" font-weight="bold">KEY</tspan></text>
    <text x="210" y="245" fill="#ffffff" font-size="20"><tspan fill="#ffffff" font-weight="bold">METRICS</tspan></text>
    <% @lean_canvas_items_map[:KEY_METRICS].each_with_index do |lean_canvas_item, index| %>
      <text x="210" y="<%= 245 + 20 * (index + 1) %>" fill="#ffffff" font-size="15"><%= lean_canvas_item.value %></text>
    <% end %>

    <rect width="200" height="400" x="400" id="unique_value_proposition"/>
    <text x="410" y="25" fill="#ffffff" font-size="20"><tspan fill="#ffffff" font-weight="bold">UNIQUE</tspan></text>
    <text x="410" y="45" fill="#ffffff" font-size="20"><tspan fill="#ffffff" font-weight="bold">VALUE</tspan></text>
    <text x="410" y="65" fill="#ffffff" font-size="20"><tspan fill="#ffffff" font-weight="bold">PROPOSITION</tspan></text>
    <% @lean_canvas_items_map[:UNIQUE_VALUE_PROPOSITION].each_with_index do |lean_canvas_item, index| %>
      <text x="410" y="<%= 65 + 20 * (index + 1) %>" fill="#ffffff" font-size="15"><%= lean_canvas_item.value %></text>
    <% end %>

    <rect width="200" height="200" x="600" id="unfair_advantage"/>
    <text x="610" y="25" fill="#ffffff" font-size="20"><tspan fill="#ffffff" font-weight="bold">UNFAIR</tspan></text>
    <text x="610" y="45" fill="#ffffff" font-size="20"><tspan fill="#ffffff" font-weight="bold">ADVANTAGE</tspan></text>
    <% @lean_canvas_items_map[:UNFAIR_ADVANTAGE].each_with_index do |lean_canvas_item, index| %>
      <text x="610" y="<%= 45 + 20 * (index + 1) %>" fill="#ffffff" font-size="15"><%= lean_canvas_item.value %></text>
    <% end %>

    <rect width="200" height="200" x="600" y="200" id="channels"/>
    <text x="610" y="225" fill="#ffffff" font-size="20"><tspan fill="#ffffff" font-weight="bold">CHANNELS</tspan></text>
    <% @lean_canvas_items_map[:CHANNELS].each_with_index do |lean_canvas_item, index| %>
      <text x="610" y="<%= 225 + 20 * (index + 1) %>" fill="#ffffff" font-size="15"><%= lean_canvas_item.value %></text>
    <% end %>

    <rect width="200" height="400" x="800" id="customer_segments"/>
    <text x="810" y="25" fill="#ffffff" font-size="20"><tspan fill="#ffffff" font-weight="bold">CUSTOMER</tspan></text>
    <text x="810" y="45" fill="#ffffff" font-size="20"><tspan fill="#ffffff" font-weight="bold">SEGMENTS</tspan></text>
    <% @lean_canvas_items_map[:CUSTOMER_SEGMENTS].each_with_index do |lean_canvas_item, index| %>
      <text x="810" y="<%= 45 + 20 * (index + 1) %>" fill="#ffffff" font-size="15"><%= lean_canvas_item.value %></text>
    <% end %>

    <rect width="500" height="200" y="400" id="cost_structure"/>
    <text x="10" y="425" fill="#ffffff" font-size="20"><tspan fill="#ffffff" font-weight="bold">COST STRUCTURE</tspan></text>
    <% @lean_canvas_items_map[:COST_STRUCTURE].each_with_index do |lean_canvas_item, index| %>
      <text x="10" y="<%= 425 + 20 * (index + 1) %>" fill="#ffffff" font-size="15"><%= lean_canvas_item.value %></text>
    <% end %>

    <rect width="500" height="200" x="500" y="400" id="revenue_streams"/>
    <text x="510" y="425" fill="#ffffff" font-size="20"><tspan fill="#ffffff" font-weight="bold">REVENUE STREAMS</tspan></text>
    <% @lean_canvas_items_map[:REVENUE_STREAMS].each_with_index do |lean_canvas_item, index| %>
      <text x="510" y="<%= 425 + 20 * (index + 1) %>" fill="#ffffff" font-size="15"><%= lean_canvas_item.value %></text>
    <% end %>
  </g>
  <use xlink:href="#outline" fill="#ffffff" stroke="#a9a9a9"/>
</svg>

app/views/lean_canvas_items/update.html.erb
<h2>LeanCanvasItemsController#update</h2>